import os
import re
from datetime import datetime

# PlatformIO pre-build script — runs before compilation on every build.
# Reads version.h (MAJOR/MINOR/PATCH), increments build_number.txt,
# then writes src/version_build.h with the full version string + timestamp.
Import("env")  # noqa: F821 — injected by SCons/PlatformIO


def get_version(src_dir):
    """Read MAJOR/MINOR/PATCH from src/version.h."""
    version_file = os.path.join(src_dir, "version.h")
    major, minor, patch = 1, 0, 0
    if os.path.exists(version_file):
        with open(version_file, "r") as f:
            content = f.read()
        m = re.search(r"#define\s+FW_VERSION_MAJOR\s+(\d+)", content)
        if m:
            major = int(m.group(1))
        m = re.search(r"#define\s+FW_VERSION_MINOR\s+(\d+)", content)
        if m:
            minor = int(m.group(1))
        m = re.search(r"#define\s+FW_VERSION_PATCH\s+(\d+)", content)
        if m:
            patch = int(m.group(1))
    return major, minor, patch


def increment_build(project_dir):
    """Read build_number.txt, increment by 1, write back, return new value."""
    counter_file = os.path.join(project_dir, "build_number.txt")
    build = 1
    if os.path.exists(counter_file):
        with open(counter_file, "r") as f:
            try:
                build = int(f.read().strip()) + 1
            except ValueError:
                build = 1
    with open(counter_file, "w") as f:
        f.write(str(build))
    return build


# ── Main ──────────────────────────────────────────────────────────────────────
project_dir = env.subst("$PROJECT_DIR")  # noqa: F821
src_dir = env.subst("$PROJECT_SRC_DIR")  # noqa: F821

major, minor, patch = get_version(src_dir)
build = increment_build(project_dir)
now = datetime.now()

header = """\
#pragma once
// Auto-generated by scripts/auto_version.py \u2014 DO NOT EDIT
// This file is overwritten on every build. Add version.h to git instead.

#define FW_VERSION_MAJOR   {major}
#define FW_VERSION_MINOR   {minor}
#define FW_VERSION_PATCH   {patch}
#define FW_BUILD_NUMBER    {build}
#define FW_BUILD_DATE      "{date}"
#define FW_BUILD_TIME      "{time}"
#define FW_VERSION_FULL    "{major}.{minor}.{patch}.{build}"
""".format(
    major=major,
    minor=minor,
    patch=patch,
    build=build,
    date=now.strftime("%Y-%m-%d"),
    time=now.strftime("%H:%M:%S"),
)

out_path = os.path.join(src_dir, "version_build.h")
with open(out_path, "w") as f:
    f.write(header)

print(
    "\n[version] Rotato firmware  v{}.{}.{}.{}  (built {} {})\n".format(
        major, minor, patch, build,
        now.strftime("%Y-%m-%d"), now.strftime("%H:%M:%S"),
    )
)
