import gzip
import os

# PlatformIO pre-build script — runs before compilation on every build.
# Reads data/index.html, gzip-compresses it (level 9), and writes
# src/web_ui_html.h containing the compressed bytes as a PROGMEM array.
#
# This bakes the entire web UI into firmware.bin so:
#   • OTA updates (POST /update) also deliver the latest UI in one file.
#   • "Upload Filesystem Image" (uploadfs) is no longer required.
#
# The generated header is intentionally gitignored — regenerated on every build.
Import("env")  # noqa: F821 — injected by SCons/PlatformIO

project_dir = env.subst("$PROJECT_DIR")  # noqa: F821
src_dir     = env.subst("$PROJECT_SRC_DIR")  # noqa: F821

html_path = os.path.join(project_dir, "data", "index.html")
out_path  = os.path.join(src_dir, "web_ui_html.h")

if not os.path.exists(html_path):
    print("[embed_web_ui] WARNING: data/index.html not found — skipping embed.")
else:
    with open(html_path, "rb") as f:
        raw = f.read()

    gz = gzip.compress(raw, compresslevel=9)

    # Format as a C hex array:  0x1f, 0x8b, 0x08, ...
    hex_bytes = ", ".join("0x{:02x}".format(b) for b in gz)

    header = (
        "#pragma once\n"
        "// Auto-generated by scripts/embed_web_ui.py \u2014 DO NOT EDIT\n"
        "// Rebuild firmware after changing data/index.html.\n"
        "#include <pgmspace.h>\n"
        "\n"
        "static const uint8_t  WEB_UI_HTML_GZ[]  PROGMEM = {{{bytes}}};\n"
        "static const uint32_t WEB_UI_HTML_GZ_LEN          = {length}UL;\n"
    ).format(bytes=hex_bytes, length=len(gz))

    with open(out_path, "w") as f:
        f.write(header)

    ratio = 100.0 * (1.0 - len(gz) / len(raw))
    print(
        "\n[embed_web_ui] index.html  {} bytes  →  {} bytes gzip ({:.0f}% smaller).\n".format(
            len(raw), len(gz), ratio
        )
    )
