#pragma once
// Auto-generated by scripts/auto_version.py — DO NOT EDIT
// This file is overwritten on every build. Add version.h to git instead.

#define FW_VERSION_MAJOR   1
#define FW_VERSION_MINOR   0
#define FW_VERSION_PATCH   0
#define FW_BUILD_NUMBER    4
#define FW_BUILD_DATE      "2026-03-26"
#define FW_BUILD_TIME      "11:53:00"
#define FW_VERSION_FULL    "1.0.0+4"
